basePath: /
definitions:
  health.SuccessResponse:
    properties:
      status:
        type: string
    type: object
  remote.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  remote.PushRemoteRequest:
    properties:
      baseUrl:
        type: string
      remoteName:
        type: string
      version:
        type: string
    type: object
  remote.RemoteResponse:
    properties:
      remoteName:
        type: string
      remoteURL:
        type: string
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for timekeeper backend.
  title: Timekeeper Backend API
  version: "1.0"
paths:
  /get-remote:
    get:
      consumes:
      - application/json
      description: Get a remote by name and version
      parameters:
      - description: Remote Name
        in: query
        name: remoteName
        required: true
        type: string
      - description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/remote.RemoteResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/remote.ErrorResponse'
      summary: Get a remote by name and version
      tags:
      - remote
  /health-check:
    get:
      description: Returns the status of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.SuccessResponse'
      summary: Health check endpoint
      tags:
      - health
  /push-remote:
    post:
      consumes:
      - application/json
      description: Push a new remote
      parameters:
      - description: Remote
        in: body
        name: remote
        required: true
        schema:
          $ref: '#/definitions/remote.PushRemoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/remote.RemoteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/remote.ErrorResponse'
      summary: Push a new remote
      tags:
      - remote
swagger: "2.0"
